sonar.projectKey=frontend_SENA-Intellij
sonar.projectName=ERP_SENA_FRONTEND
sonar.host.url=http://localhost:9000
sonar.login=*******
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**

